version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    version_requirement_updates: 'widen_ranges'
    target_branch: 'version/1'
    allowed_updates:
      - match:
          update_type: 'all'
          dependency_type: 'direct'
