name: Build and test codebase

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm install --global npm
          npm install --ignore-scripts
          npm run build
          npm test
        env:
          CI: true
