name: Publish nightly packages

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm install --global npm
      - run: npm ci
      - run: npm test
      - run: lerna publish --canary --preid nightly --dist-tag nightly --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
