name: Publish nightly packages

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: |
        corepack enable
        corepack prepare pnpm@7.1.6 --activate
        pnpm install --ignore-scripts
        pnpm build
        pnpm test
        pnpm publish:nightly
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
